import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const LocaleSwitcher = () => {
  const {
    locales = [],
    locale: activeLocale,
    pathname,
    query,
    asPath,
  } = useRouter();

  return (
    <div className="body-bold flex items-center text-6xl text-white">
      <ul className="body-bold flex w-full justify-end">
        {locales.map((locale) => {
          const styles =
            locale === activeLocale
              ? "mr-2 border bg-red-900 text-xl text-white "
              : "mr-2 border bg-white text-xl text-red-900";
          return (
            <li className={styles} key={locale}>
              <Link
                href={{ pathname, query }}
                as={asPath}
                locale={locale}
                legacyBehavior
              >
                {locale?.toUpperCase()}
              </Link>
            </li>
          );
        })}
      </ul>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LocaleSwitcher />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Link
            href="/protected"
            className="cursor-pointer bg-white p-4 text-6xl text-red-900 "
          >
            2. PRESS THIS TO CHECK AUTH ISSUE
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
