import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center text-4xl">
        <p>Welcome to sandbox</p>
      </main>
    </>
  );
};

export default Home;
